# Infraestructura para Jellyfin con proxy reverso
# Elementos a desplegar:
# 1. Firewalls:
#    - firewall-jellyfin (permite tráfico HTTP/HTTPS a proxy-server)
#    - firewall-internal (permite tráfico entre instancias)
# 2. Instancias:
#    - proxy-server (Nginx)
#    - app-server (Jellyfin)

resources:
  # Firewall para el proxy (HTTP desde Internet)
  - name: firewall-jellyfin
    type: compute.v1.firewall
    properties:
      network: https://www.googleapis.com/compute/v1/projects/arquisoft-2023-9878/global/networks/default
      priority: 1000
      direction: INGRESS
      sourceRanges: ["0.0.0.0/0"]
      targetTags: ["proxy"]
      allowed:
        - IPProtocol: TCP
          ports: [80]

  # Firewall interno (solo proxy-server puede acceder a app-server)
  - name: firewall-internal
    type: compute.v1.firewall
    properties:
      network: https://www.googleapis.com/compute/v1/projects/arquisoft-2023-9878/global/networks/default
      priority: 1010
      direction: INGRESS
      sourceTags: ["proxy"]
      targetTags: ["jellyfin-server"]
      allowed:
        - IPProtocol: TCP
          ports: [8096]

  # Proxy Server (Nginx - e2-micro)
  - type: compute.v1.instance
    name: proxy-server
    properties:
      zone: us-central1-a
      machineType: https://www.googleapis.com/compute/v1/projects/arquisoft-2023-9878/zones/us-central1-a/machineTypes/e2-micro
      tags:
        items: ["proxy"]
      disks:
        - deviceName: boot
          type: PERSISTENT
          boot: true
          autoDelete: true
          initializeParams:
            sourceImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
      networkInterfaces:
        - network: https://www.googleapis.com/compute/v1/projects/arquisoft-2023-9878/global/networks/default
          networkIP: 10.128.0.62
          accessConfigs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      metadata:
        items:
          - key: startup-script
            value: |
              #!/bin/bash
              sudo apt-get update -y
              sudo apt-get install -y git python3 python3-pip
              git clone https://github.com/MariaAmor8/ReverseProxyGCP.git /home/proxy
              pip3 install -r /home/proxy/requirements.txt
              nohup python3 /home/proxy/mainProxy.py > /home/proxy/proxy.log 2>&1 &

  # App Server (Jellyfin - e2-micro)
  - type: compute.v1.instance
    name: app-server
    properties:
      zone: us-central1-a
      machineType: https://www.googleapis.com/compute/v1/projects/arquisoft-2023-9878/zones/us-central1-a/machineTypes/e2-micro
      tags:
        items: ["jellyfin-server"]
      disks:
        - deviceName: boot
          type: PERSISTENT
          boot: true
          autoDelete: true
          initializeParams:
            sourceImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
      networkInterfaces:
        - network: https://www.googleapis.com/compute/v1/projects/arquisoft-2023-9878/global/networks/default
          networkIP: 10.128.0.63  # IP fija para el proxy
          accessConfigs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      metadata:
        items:
          - key: startup-script
            value: |
              #!/bin/bash
              sudo apt-get update -y
              sudo apt-get install -y git
              git clone https://github.com/MariaAmor8/ReverseProxyGCP.git /tmp/repo
              sudo cp -r /tmp/repo/songs /songs
              sudo chmod -R 755 /songs
              sudo apt-get install curl gnupg -y
              curl -fsSL https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/jellyfin.gpg
              echo "deb [arch=$(dpkg --print-architecture)] https://repo.jellyfin.org/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
              sudo apt-get update
              sudo apt-get install jellyfin -y
              sudo ufw allow from 10.128.0.62 to any port 8096  # Solo permite proxy-server
              sudo ufw enable